### ISSUE TITLE
Support animationData from URL.

### ISSUE THREAD

**Issue by gl2748** [chenqingspring/react-lottie#93]
Is there any support for passing a URL to the animationData prop?

**Comment by zyzski** [comment]
> Is there any support for passing a URL to the animationData prop?

i'd create a component to fetch the animationData from the url and pass it to Lottie

**Comment by raynoo** [comment]
@gl2748 I didn't find anything mentioned about it in the docs, but looks like the underlying [`lottie-web` does accept a `path` option](https://github.com/airbnb/lottie-web#html) instead of `animationData`. This works for me,

```js
import Lottie from 'react-lottie';
<Lottie 
  options={{
    loop: false, 
    path: 'https://labs.nearpod.com/bodymovin/demo/pancakes/data.json',
  }}
  height: 200,
  width: 300,
/>
```

It might be more straightforward to have a `path` prop on `Lottie` that is then explicitly passed down to `lottie-web`. But this works too since any options you set [is passed down](https://github.com/chenqingspring/react-lottie/blob/master/src/index.js#L30) (on top of default options).

**Comment by gl2748** [comment]
@raynoo thanks!

**Comment by mbj36** [comment]
@raynoo Thanks you!

**Comment by kumarsks619** [comment]
@raynoo thanks a lot!

**Comment by m7amad-7asan** [comment]
@raynoo Thanks

**Comment by davidmann4** [comment]
this needs to be in readme.md 

let me create a PR real quick

**Comment by rodrigobacelli** [comment]
Path needs to be added to LottieOptions type
